export default [
  'Accurint',
  'Adobe Creative Suite',
  'Anima',
  'ArcGIS',
  'Asana',
  'Atavist',
  'Audiogram',
  'AWS',
  'Ballotopedia',
  'Bootstrap',
  'Brackets',
  'Browserstack',
  'CartoDB',
  'CensusReporter',
  'Chartbeat',
  'Clickability',
  'CometDocs',
  'Coral Project Ask',
  'Coral Project Talk',
  'csvkit',
  'D3',
  'data.world',
  'Datakit',
  'Datawrapper',
  'Dbpedia',
  'Dedupe',
  'Django',
  'DocumentCloud',
  'Elasticsearch',
  'Envision',
  'Microsoft Excel',
  'Census FactFinder',
  'Figma',
  'Flourish',
  'Freshbooks',
  'Google Fusion Tables',
  'geocode.io',
  'GeoJSON.io',
  'Github',
  'Gitlab',
  'Google Analytics',
  'Google Civic Information API',
  'Google Docs',
  'Google Sheets',
  'Google Slides',
  'Hearken',
  'Heroku',
  'HighCharts',
  'Adobe Indesign',
  'Infogram',
  'Intercom',
  'Invision',
  'JavaScript',
  'Node.js',
  'Jupyter Notebooks',
  'JWPlayer',
  'Leaflet',
  'Mapbox',
  'Merlin',
  'Metrics for News',
  'Microsoft Teams',
  'Navicat',
  'OpenRefine',
  'OpenSecrets',
  'Otter.ai',
  'PACER',
  'Panda',
  'PostGIS',
  'PostgreSQL',
  'Postico',
  'Python',
  'QGIS',
  'R',
  'ProPublica Congress API',
  'RMarkdown',
  'RStudio',
  'Ruby',
  'Salesforce',
  'SauceLabs',
  'Scribble Live',
  'Semaphore',
  'Sentry',
  'Sequel Pro',
  'Sharepoint',
  'Sketch',
  'Skype',
  'Slack',
  'SoundCite',
  'SoundCloud',
  'Storefront',
  'Stripe',
  'Sublime Text',
  'Tableau',
  'Tabula',
  'Temi',
  'TimelineJS',
  'TravisCI',
  'Trello',
  'Twitter',
  'Tweetdeck',
  'Visual Studio Code',
  'WhatsApp',
  'WordPress',
  'Zamzar',
  'Zeppelin',
  'Zoom',
  'Adobe Illustrator',
  'Adobe Photoshop',
  'Adobe Premiere Pro',
  'Adobe After Effects',
  'Adobe Audition',
  'Adobe XD',
  'Photo Mechanic',
  'Trint',
  'Parse.ly',
  'Crowdtangle',
  'Microsoft Word',
  'Microsoft Office 365',
  'Dropbox',
  'Box',
  'Google Drive',
  'Facebook Pages',
  'Headliner',
  'Descript',
  'MuckRock',
  'FOIA Machine',
  'Klaxon',
  'R',
]
